### ISSUE TITLE
License change question

### ISSUE THREAD

**Issue by Happy-Ferret** [AlbanBedel/scummc#12]
Hi.

I'd like to take over maintainership/create an active hard fork of this project (With a preference for the latter. I already have a few ideas in regards to the build system, GUI tooling, documentation and syntax changes).

Would you and the other contributors consider a change to GPL3?

**Comment by AlbanBedel** [comment]
All the code is under "GPL2 or later" so you can just start using GPL3 in your own releases right away. Good luck :)

As I'm not working on ScummC anymore it might later make sense to put a link to your project in the README.
