### ISSUE TITLE
Makefile invalid

### ISSUE THREAD

**Issue by DivineDominion** [AlbanBedel/scummc#2]
After running `configure` on my 64bit Mac Mini 2011, `make` doesn't work:

```
$ make
Makefile:125: *** target pattern contains no `%'.  Stop.
```

Since line 125 reads `$(foreach target,$(TARGETS),$(eval $(call TARGET_template,$(target))))`, It could be that some line before that contains letters that were parsed as regular expression. But I cannot easily find my way around this shell stuff, so I'm filing this issue, hoping to make progress or attract support :)

**Comment by AlbanBedel** [comment]
Which make version are you using?

**Comment by DivineDominion** [comment]
D'uh, sorry :)

GNU Make 3.81

**Comment by AlbanBedel** [comment]
Thanks to Travis CI I was able to test the build on OSX and this is now fixed.

**Comment by idleberg** [comment]
Are there plans for a patch release that contains the fix?

**Comment by AlbanBedel** [comment]
I was planning to do a new release at the time I fixed this bug, however I got side tracked with the countless other projects I have. To do a release we just need to make sure the generated archives are ok, update the README and wiki, then that could be tagged and uploaded.

**Comment by AlbanBedel** [comment]
Done, now. Let me know if there is any problem with the release.
