### ISSUE TITLE
Parsing error (scc_parse.y)

### ISSUE THREAD

**Issue by Memorix101** [AlbanBedel/scummc#3]
Hello,

I can't compile it on Windows and Linux (Ubuntu). 
All of them came to the same error

Windows output:
> make[1]: Entering directory '/home/memor/scummc-0.2.0/build.DESKTOP-I9JE0CE/i686-msys-gcc-6.3.0-debug'
Compiling scc_parse.tab.o for i686-msys-gcc-6.3.0-debug
scc_parse.tab.c: In function ‘scc_parser_parse_internal’:
/home/memor/scummc-0.2.0/scc_parse.y:84:15: error: too few arguments to function ‘scc_lex_lex’
 #define yylex scc_lex_lex
               ^
scc_parse.tab.c:1851:16: note: in expansion of macro ‘yylex’
       yychar = yylex (&yylval, &yylloc);
                ^~~~~
In file included from /home/memor/scummc-0.2.0/scc_parse.y:53:0:
/home/memor/scummc-0.2.0/scc_lex.h:90:5: note: declared here
 int scc_lex_lex(YYSTYPE *lvalp, YYLTYPE *llocp,scc_lex_t* lex);
make[1]: *** [Makefile:185: scc_parse.tab.o] Error 1
make[1]: Leaving directory '/home/memor/scummc-0.2.0/build.DESKTOP-I9JE0CE/i686-msys-gcc-6.3.0-debug'
make: *** [Makefile:119: i686-msys-gcc-6.3.0-debug_progs] Error 2

Linux output

> scc_parse.tab.c: In function ‘scc_parser_parse_internal’:
/home/memorix101/scummc-0.2.0/scc_parse.y:84:15: error: too few arguments to function ‘scc_lex_lex’
 #define yylex scc_lex_lex
               ^
scc_parse.tab.c:1851:16: note: in expansion of macro ‘yylex’
       yychar = yylex (&yylval, &yylloc);
                ^~~~~
In file included from /home/memorix101/scummc-0.2.0/scc_parse.y:53:0:
/home/memorix101/scummc-0.2.0/scc_lex.h:90:5: note: declared here
 int scc_lex_lex(YYSTYPE *lvalp, YYLTYPE *llocp,scc_lex_t* lex);
Makefile:184: recipe for target 'scc_parse.tab.o' failed
make[1]: *** [scc_parse.tab.o] Error 1
make[1]: Leaving directory '/home/memorix101/scummc-0.2.0/build.ubuntu/i686-gnu-gcc-6.3.0-debug'
Makefile:119: recipe for target 'i686-gnu-gcc-6.3.0-debug_progs' failed
make: *** [i686-gnu-gcc-6.3.0-debug_progs] Error 2

**Comment by AlbanBedel** [comment]
Which version of bison are you using?

**Comment by Memorix101** [comment]
All systems are running on 3.0.4, but do you think a newer version is the issue ?

**Comment by Memorix101** [comment]
I installed bison 1.30 now. Still the same result.

**Comment by AlbanBedel** [comment]
Sorry for the long delay in responding here. I missed that you are using version 0.2, please use the current git version this bug is fixed there.
