### ISSUE TITLE
It's compiled ! So... What now? 

### ISSUE THREAD

**Issue by Ovamprod** [AlbanBedel/scummc#4]
Hi ! Thanks for keeping ScummC updated ! That's awesoooooome
We compiled successfully, but ScummVM cannot recognize files as a game (and therefore can't read it). 
Can you give us a hint, please?

**Comment by Ovamprod** [comment]
Ps: we have no "Day of the Tentacle" file

**Comment by AlbanBedel** [comment]
You need to either patch ScummVM or generate a DotT compatible file. Patching ScummVM is the recommended way as it disable any game specific hacks. However the patch probably don't apply to the current version and there is really few chance to hit such a hack.

To generate a DotT compatible version of an example game build it with "make tentacle". This will output 3 files named tentacle.000, tentacle.001 and monster.sou that are then recognized as DotT by ScummVM.

**Comment by Ovamprod** [comment]
Hi !
Yay, we did it ! Thanks so much, we are delighted to see the compiler work and are excited to be able to get to coding our own little game. 
Thanks again, for answering and for keeping scummC alive !
