### ISSUE TITLE
Specify build folder

### ISSUE THREAD

**Issue by idleberg** [AlbanBedel/scummc#8]
Currently, the compiled binaries are in the folder named so:

`build.<hostname>.<compiler_name_and_version>`

Would it be possible to add an argument to the `makefile` that overrides that default scheme? This would be useful to generate builds in reproducible output folders.

**Comment by AlbanBedel** [comment]
The build system has been designed to allow building for multiple targets on multiple hosts sharing the same source directory, all at the same time. So adding back the capability to build for a single target is not trivial, however you can easily get the build directory by parsing `config.$HOST.mk`, or using `make targets`.

**Comment by idleberg** [comment]
Thank you Alban. At the time when I opened this issue, the naming was a concern. I have created a formula for the Homebrew package manager, so building the scummc tools becomes much easier. However, it turned out that Homebrew has some helpers that made a reproducible output folder unnecessary. So I guess we can close this issue.
